### ISSUE TITLE
Organisation?

### ISSUE THREAD

**Issue by tokorv** [RedCubeDev-ByteSpace/ReCT-Go-Compiler#1]
### **Why isn't this on Discord?**
I am at college right now and their network blocks out Discord so I will ask this here.

### **Should we get organised?**
By "organised" I mean we know what needs to be done and know what each other are working on. So, for example, we could set up a **Trello board** or **GitHub Kanban** to help manage the project better. - I feel like we would be more productive.

**Comment by WillTheDeveloper** [comment]
I think we should setup a GitHub Kanban. Trello is pretty poo and its virtually the same. (I'm friends with @tokorv irl)

**Comment by tokorv** [comment]
> I think we should setup a GitHub Kanban. Trello is pretty poo and its virtually the same. (I'm friends with @tokorv irl)

**Trello** > **GitHub Kanban** in my opinion. You get more features in **Trello**, the only big advantage with **GitHub Kanban** can connect with issues and pull requests.

**Comment by Khhs167** [comment]
I dont really care, i like trello, but kanban is ok too.

**Comment by tokorv** [comment]
I

**Comment by mauro-balades** [comment]
Or set a milestone for the repo...
