### ISSUE TITLE
Give jimmy something to do

### ISSUE THREAD

**Issue by Khhs167** [RedCubeDev-ByteSpace/ReCT-Go-Compiler#3]
I am bored and idk what to do. Please help me.

**Comment by tokorv** [comment]
Could start a command line interface similar to the one rctc has. Though I admit it is a bit premature, you could start it if you wanted something simple to make. Think `compiler test/test1.rct` (which passes the filename into `lexer.Lex()` and then parsing the tokens) but it could also have flags similar to rctc using Go's flag package.

**Comment by Khhs167** [comment]
I've got a task now, closing.
