### ISSUE TITLE
Proposal for function calls to be handled by expression instead of identifier

### ISSUE THREAD

**Issue by hrszpuk** [RedCubeDev-ByteSpace/ReCT-Go-Compiler#32]
## Description
Currently, function calls are based on identifier.
This works for traditional function calls such as `functionExample()`, but it would be much more useful for function calls to be based on an expression. This would allow for an infinitely more expressible language and would open ReCT up to more complex, and therefore useful, expressions. Below is a list of expressions that *could* be possible if function calls were based on expressions.

**Potential Expressions:**
- `(amICool ? veryCool : notVeryCool)()`
- `exampleFunc()()`
- ...more

This is currently not possible using the ReCT Go Compiler.

### Example:
**ReCT code**
![](https://media.discordapp.net/attachments/751172723589382355/1072621925983076362/Screenshot_20230207_215632.png?width=636&height=247)
**Compilation message**
![](https://cdn.discordapp.com/attachments/751172723589382355/1072621890113372302/Screenshot_20230207_215623.png)

**Comment by mr-cheffy** [comment]
quick

**Comment by hrszpuk** [comment]
> quick

I *am* speed.

**Comment by mr-cheffy** [comment]
Hello speed, I am dad

**Comment by hrszpuk** [comment]
God damn it, you got me Mauro.
